source 'https://rubygems.org'

# Specify your gem's dependencies in cocoapods-echo.gemspec
gemspec

group :development do
  gem 'cocoapods'
  gem 'bacon'
  gem 'mocha-on-bacon'
  gem 'mocha', '~> 0.11.4'
  gem 'rake'
  gem 'prettybacon', :git => 'https://github.com/irrationalfab/PrettyBacon.git', :branch => 'master'
end
